### ISSUE TITLE
Why The Description Says Real Source code

### ISSUE THREAD

**Issue by ElPro7777** [MemeHoovy/sonic.exe-2.5-3.0#1]
### What is your question?

Why The Description Says Real Source code?

**Comment by MemeHoovy** [comment]
because it is real dumbass

**Comment by ElPro7777** [comment]
So there are 2 Source Codes For the exe 2.5 https://github.com/DuskieWhy/exe-2.5-code and this

**Comment by MemeHoovy** [comment]
yeah, and mine is attempting to restore it
