### ISSUE TITLE
Some Restoration ideas

### ISSUE THREAD

**Issue by ElPro7777** [MemeHoovy/sonic.exe-2.5-3.0#3]
### What feature do you want to get added on the base engine?

YCR Encore Official Charted
Better Encore images (why there is sunky making pee in the triple trouble image)
Finished Encore Trouble (Triple Trouble Encore)
Her World
Mania
Final Escape/Too Far with his original mechanic (at the end of triple trouble the game was supposed to crash and later when you tried to open it again Final Escape/Too far Starts)
Sunshine Encore

**Comment by LEVIXDDLMAO** [comment]
I can work on Triple Trouble Encore chart thats only i can do

**Comment by ElPro7777** [comment]
i mean the tails part finished and the unfinished parts

**Comment by MemeHoovy** [comment]
alright

**Comment by LEVIXDDLMAO** [comment]
> i mean the tails part finished and the unfinished parts

yeah i can work on there chart

**Comment by MemeHoovy** [comment]
Idk if some of these I can do if the assets are publicly available or they exist

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by ElPro7777** [comment]
the triple trouble encore starts with sonic.exe because the tails part wasnt finished

**Comment by ElPro7777** [comment]
and also the Sonic.exe 3rd part in triple trouble was fixed because eggman was singing EXE part
